name: NPM - Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  Branches: master
  MainBranch: master
  NPMRegistry: https://registry.npmjs.org/
  InstallCommand: npm i
  DeployCommand: npm run deploy
  Organization: lowcodeunit
  Repository: public-web-blog
  Output: ./build
